### PR TITLE
#03 - JSON Built in visitor

### PR DESCRIPTION
**Pull request by DanielMaida**
- Now JSON is built in visitor
- PolicyBuilder class refactoring
- Output Tests added

---
This change is [Reviewable](https://reviewable.io/reviews/pauloborba/pol/5)

### CODE REVIEW

**Comment by pauloborba** [comment]
Reviewed 11 of 13 files at r1.
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[PolicyLanguageCore/src/production/PolicyBuilder.java, line 53 at r1](https://reviewable.io:443/reviews/pauloborba/pol/5#-KcZJTP2spybAgWYGGej:-KcZJTP3ZcqwbsGXpzlT:bsjhm9q) ([raw file](https://github.com/pauloborba/pol/blob/c0c92f82c72bb63a3ce09b221d484d5c9cfdc365/PolicyLanguageCore/src/production/PolicyBuilder.java#L53)):*
> ```Java
> 		visitTree(inputPolicies);
> 
> 		ArrayList<JSONObject> policies = visitor.getPolicies();
> ```

por que mudou? parece perder abstração

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/pol/5)*

**Comment by DanielMaida** [comment]
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[PolicyLanguageCore/src/production/PolicyBuilder.java, line 53 at r1](https://reviewable.io:443/reviews/pauloborba/pol/5#-KcZJTP2spybAgWYGGej:-KcdBR5xmym2AS6pqMHz:bwtw6qw) ([raw file](https://github.com/pauloborba/pol/blob/c0c92f82c72bb63a3ce09b221d484d5c9cfdc365/PolicyLanguageCore/src/production/PolicyBuilder.java#L53)):*
<details><summary><i>Previously, pauloborba (Paulo Borba) wrote…</i></summary><blockquote>

por que mudou? parece perder abstração
</blockquote></details>

Esse objeto Policy só era necessário quando o JSON era construído fora do visitor, que aí os atributos das Policies eram adquiridos no visitor e capturados na classe PolicyBuilder para a construção do JSON (que talvez seja até melhor trocar o nome para PolicyPrinter). Agora todos os atributos estão sendo capturados no visitor e o JSON está sendo criado no visitor também, todas as variáveis (no visitor) estão com nomes que ilustram quais são as partes das policies que estão sendo criadas.

Resumindo : Agora o JSON está sendo construído durante a visitação da árvore, portanto, o objeto para armazenar os atributos das policies não é mais necessário.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/pol/5)*

**Comment by pauloborba** [comment]
Reviewed 1 of 13 files at r1.
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/pol/5)*

**Comment by pauloborba** [comment]
Reviewed 1 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pauloborba/pol/5)*

**Pull request merged**
